# Meta
name: 비주얼씨어터컴퍼니 꽃
description: ‘비주얼씨어터 꽃’은 시각예술과 공연예술이 통합된 시각연극 Visual Theater를 추구하는 공연예술단체입니다.
url: http://visualtheater.kr
baseurl: ''

en:
  name: Visual theater company, CCOT
  description: description goes here.
  url: http://visualtheater.kr/en/

timezone: 'Asia/Seoul'
permalink: pretty

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: :compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge

# collections
collections:
  works:
    output: true
    permalink: /work/:path/
  en_works:
    output: true
    permalink: /en/work/:path/
  texts:
    output: true
    permalink: /text/:path/
  press:
    output: false

defaults:
  -
    scope:
      path: _works
    values:
      layout: work
  -
    scope:
      path: _en_works
    values:
      layout: en/work
  -
    scope:
      path: _texts
    values:
      layout: text
