# Meta
name: 비주얼씨어터 꽃
description: ‘비주얼씨어터 꽃’은 시각예술과 공연예술이 통합된 시각연극 Visual Theater를 추구하는 공연예술단체입니다.
url: http://visualtheater.kr
baseurl: ''

en:
  name: CCOT
  description: CCOT has worked on alternative spaces and outdoor, pursuing visual theater, material theater, interdisciplinary theater, and self-performance.
  url: http://visualtheater.kr/en/

timezone: 'Asia/Seoul'
permalink: pretty

# SEO
facebook:
  app_id: 618140558345676
  publisher: https://www.facebook.com/visualtheaterccot
logo: /assets/images/template/logo.png
google_site_verification: dnwLvZ3C5wU5YCtIEPxiVDcL9Wr019enF7IOYXz9xII

google_analytics: UA-81266340-1

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

sass:
  style: :compressed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# collections
collections:
  works:
    output: true
    permalink: /work/:path/
  en_works:
    output: true
    permalink: /en/work/:path/
  texts:
    output: true
    permalink: /text/:path/
  en_texts:
    output: true
    permalink: /en/text/:path/
  press:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      image:
        twitter: /assets/images/work/masseur/IMG_2165.jpg
        facebook: /assets/images/work/masseur/IMG_2165.jpg
  -
    scope:
      path: _works
    values:
      layout: work
  -
    scope:
      path: _en_works
    values:
      layout: en/work
  -
    scope:
      path: _texts
    values:
      layout: text
  -
    scope:
      path: _en_texts
    values:
      layout: en/text
